name: sign_language_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.11.1
  tflite_flutter: ^0.11.0
  image: ^4.5.4
  google_fonts: ^6.2.1
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/models/asl_model.tflite
